# Generated by Django 3.0.3 on 2020-02-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reporter',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='reporter',
            new_name='author',
        ),
    ]
