# Generated by Django 3.0.3 on 2020-02-08 16:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='last_edited_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 8, 16, 56, 47, 958561, tzinfo=utc), verbose_name='Last edited on'),
        ),
    ]
